### ISSUE TITLE
Startindex cannot be larger than length of string

### ISSUE THREAD

**Issue by Grip555** [Sora-yx/SADX-Randomizer#4]
Not sure if it's got to do with this mod, or the mod manager as a whole.

I get it whenever I try and run SADXModManager. I have the latest versions of mod manger and the randomiser.

**Comment by Sora-yx** [comment]
Hello, this is not an issue with Randomizer, but the mod manager. This error usually happens when you have a "mod.ini" file in your SADX "mods" folder. 
Make sure all the mods you are using are in a subfolder, and make sure that ALL those subfolders are in the SADX "mods" folder.
